PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX worlds: <https://worlds.wazoo.tech/>

INSERT DATA {
    # Mercury
    worlds:Mercury a schema:Planet ;
        schema:name "Mercury" ;
        schema:description "The smallest planet in the Solar System and the closest to the Sun." ;
        schema:alternateName "Hermes" ;
        schema:distance "0.39"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Mercury_(planet)> .

    # Venus
    worlds:Venus a schema:Planet ;
        schema:name "Venus" ;
        schema:description "The second planet from the Sun and the hottest planet in our solar system." ;
        schema:alternateName "Aphrodite" ;
        schema:distance "0.72"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Venus> .

    # Earth
    worlds:Earth a schema:Planet ;
        schema:name "Earth" ;
        schema:description "Our home planet and the only astronomical object known to harbor life." ;
        schema:alternateName "Terra" ;
        schema:distance "1.00"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Earth> .

    # Mars
    worlds:Mars a schema:Planet ;
        schema:name "Mars" ;
        schema:description "Often called the 'Red Planet' due to iron oxide prevalent on its surface." ;
        schema:alternateName "Ares" ;
        schema:distance "1.52"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Mars> .

    # Jupiter
    worlds:Jupiter a schema:Planet ;
        schema:name "Jupiter" ;
        schema:description "The largest planet in the Solar System, a gas giant with a Great Red Spot." ;
        schema:alternateName "Zeus" ;
        schema:distance "5.20"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Jupiter> .

    # Saturn
    worlds:Saturn a schema:Planet ;
        schema:name "Saturn" ;
        schema:description "Adorned with a dazzling, complex system of icy rings." ;
        schema:alternateName "Cronus" ;
        schema:distance "9.58"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Saturn> .

    # Uranus
    worlds:Uranus a schema:Planet ;
        schema:name "Uranus" ;
        schema:description "An ice giant with a unique tilt, rotating nearly on its side." ;
        schema:alternateName "Ouranos" ;
        schema:distance "19.22"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Uranus> .

    # Neptune
    worlds:Neptune a schema:Planet ;
        schema:name "Neptune" ;
        schema:description "The most distant major planet orbiting our Sun, dark, cold and whipped by supersonic winds." ;
        schema:alternateName "Poseidon" ;
        schema:distance "30.05"^^xsd:decimal ;
        schema:identifier <https://en.wikipedia.org/wiki/Neptune> .
}

